name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make -j8
      run: make -j8

  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: make -j8
      run: make -j8
